[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "."

# Redirect API calls to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all paths to index.html for SPA routing
# But exclude JavaScript files and other assets
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
  # Important: Don't redirect these file types
  conditions = {Path = ["*.js", "*.css", "*.jpg", "*.png", "*.gif", "*.svg", "*.ico", "/api/*", "/.netlify/functions/*"]}

# Fix JavaScript content type issues - specifically target dist directory files
[[headers]]
  for = "/dist/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

# General JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"
    
# Set security headers for all paths
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"

# Set CORS headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization" 